### ISSUE TITLE
Hitting a NumberFormatException when running a maven launch configuration when ANSI integration is enabled

### ISSUE THREAD

**Issue by nicksisler** [eclipse-platform/eclipse.platform.debug#92]
Specifically it appears to be during the maven-assembly-plugin execution.

Here's an example stack trace:
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 873
java.lang.NumberFormatException: For input string: "1;[[["
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:668)
at java.base/java.lang.Integer.valueOf(Integer.java:999)
at org.fusesource.jansi.io.AnsiOutputStream.write(AnsiOutputStream.java:199)
at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:137)
at java.base/java.io.PrintStream.write(PrintStream.java:568)
at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:304)
at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132)
at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:205)
at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
at java.base/java.io.PrintStream.write(PrintStream.java:698)
at java.base/java.io.PrintStream.print(PrintStream.java:863)
at java.base/java.io.PrintStream.println(PrintStream.java:1031)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by iloveeclipse** [comment]
Nothing in the stack is related to Eclipse.
